services:
  pgcat:
    image: ghcr.io/postgresml/pgcat:latest
    ports:
      - "6432:6432"
      - "9930:9930"
    volumes:
      - ./pgcat.toml:/etc/pgcat/pgcat.toml

  postgres:
    image: postgres:14
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    volumes:
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=postgres
